/**********************************************************************/
/** FILE    : VirtualDataViewFilterComboCtrl.h                       **/
/** PROJECT : wxVirtualDataViewCtrl                                  **/
/** LICENSE : wxWindows Library Licence                              **/
/** PURPOSE : a custom combobox for filters User Interface           **/
/**********************************************************************/

#ifndef _WX_VIRTUAL_VIEW_FILTER_COMBO_CTRL_H_
#define _WX_VIRTUAL_VIEW_FILTER_COMBO_CTRL_H_


#include <wx/VirtualDataView/VirtualDataViewDefs.h>
#include <wx/combo.h>

extern const char wxVirtualDataViewFilterComboCtrlNameStr[];

class WXDLLIMPEXP_VDV wxVirtualDataViewFilterCtrl;
class WXDLLIMPEXP_VDV wxVirtualDataViewFilterPanel;
class WXDLLIMPEXP_VDV wxVirtualDataViewFilterPopup;
class WXDLLIMPEXP_VDV wxVirtualIDataModel;
class WXDLLIMPEXP_VDV wxVirtualIStateModel;
class WXDLLIMPEXP_VDV wxVirtualDataViewFilter;
class WXDLLIMPEXP_VDV wxComboboxState;

/** \class wxVirtualDataViewFilterComboCtrl : a custom combobox for filters User Interface.
  */
class WXDLLIMPEXP_VDV wxVirtualDataViewFilterComboCtrl : public wxComboCtrl
{
    public:

        //constructors & destructor
        wxVirtualDataViewFilterComboCtrl(void);                                     ///< \brief default constructor. Create() must be called manually
        wxVirtualDataViewFilterComboCtrl(wxWindow *pParent,
                             wxWindowID id = wxID_ANY,
                             const wxPoint& pos = wxDefaultPosition,
                             const wxSize& size = wxDefaultSize,
                             long lStyle = 0,
                             const wxValidator& validator = wxDefaultValidator,
                  wxString sName = wxVirtualDataViewFilterComboCtrlNameStr);        ///< \brief constructor
        virtual ~wxVirtualDataViewFilterComboCtrl(void);                            ///< \brief destructor

        //override
        virtual void Popup(void);                                                   ///< \brief show the popup
        virtual void Dismiss(void);                                                 ///< \brief dismiss the popup

        //main components
        wxVirtualDataViewFilterPanel*   GetFilterPanel(void);                       ///< \brief access to the filter panel
        wxVirtualDataViewFilterCtrl*    GetFilterControl(void);                     ///< \brief access to the filter control

        //fill filter
        virtual void            InitFilter(wxVirtualIDataModel *pSrcModel,
                                           size_t uiField,
                                           wxVirtualIStateModel *pStateModel);      ///< \brief fill the filter with data from a source model

        //generate filter
        void SetState(wxComboboxState *pState);                                     ///< \brief set the combobox state
        wxComboboxState* GetState(void);                                            ///< \brief get the combobox state
        virtual wxVirtualDataViewFilter* GenerateFilter(void);                      ///< \brief generate the filter

        //drawing
        virtual void PaintComboBox(wxDC &rDC, const wxRect &rRect);                 ///< \brief paint the combobox

        //destruction
        void AboutToBeDestroyed(void);                                              ///< \brief notify that the control is going to be destroyed

    protected:
        //data
        bool                            m_bCustomDialogPopup;                       ///< \brief true if a custom popup dialog is used
        wxVirtualDataViewFilterPopup*   m_pFilterDialog;                            ///< \brief filter dialog box
        bool                            m_bGeneratedByTextEntry;                    ///< \brief text has been generated by text entry
        wxComboboxState*                m_pComboboxState;                           ///< \brief combo-box state

        //methods
        void InitPopupWindow(void);                                                 ///< \brief initialize the popup window
        void BindEvents(void);                                                      ///< \brief bind the common events

        //wxComboCtrl override
        virtual void OnButtonClick(void);                                           ///< \brief custom button action
        virtual void DoSetPopupControl(wxComboPopup* pPopup);                       ///< \brief set to null if dialog popup is used

        //event handlers
        void OnPaintCombo(wxPaintEvent &rEvent);                                    ///< \brief override to allow paint inside different DC
        void OnTextChanged(wxCommandEvent &rEvent);                                 ///< \brief text in the combobox has changed

        //customization
        virtual wxColour GetDisplayBackColour(void) const;                          ///< \brief return the filter back colour
        virtual wxColour GetDisplayTextColour(void) const;                          ///< \brief return the filter text colour

    private:
        wxDECLARE_ABSTRACT_CLASS(wxVirtualDataViewFilterComboCtrl);
};

#endif // _WX_VLBOX_H_

